export function Home() {
  return <div class="product-page">
    <header class="product-header"><a href="/" class="product-logo"><span>✳</span> alzy</a><nav><a href="#how">Как работает</a><a href="#plans">Тарифы</a><a href="/demo">Живое демо</a></nav><a class="product-login" href="/app">Войти <span>↗</span></a></header>
    <main>
      <section class="product-hero"><div class="product-hero-copy"><div class="product-kicker"><span class="product-pulse" /> ВАШ НОВЫЙ СОТРУДНИК УЖЕ НА СВЯЗИ</div><h1>Каждая заявка<br />найдёт своё <em>время.</em></h1><p>AI-секретарь отвечает клиентам, помогает выбрать услугу и записывает в свободный слот. Вы управляете календарём и видите результат в одном кабинете.</p><div class="product-actions"><a href="/register?plan=booking" class="product-button">Попробовать 14 дней <span>↗</span></a><a href="/demo" class="product-text-button">Посмотреть демо <span>→</span></a></div><div class="product-fine">Без карты · Настройка за несколько минут</div></div><div class="product-visual"><div class="product-visual-label">ALZY / РАБОЧИЙ ДЕНЬ</div><div class="product-demo-card"><div class="product-demo-top"><span>✳</span><div><strong>Новая запись</strong><small>AI-секретарь · только что</small></div><b>✓</b></div><div class="product-demo-body"><span>10:30 — 11:30</span><strong>Стрижка</strong><p>Клиент выбрал удобное время и оставил контакты.</p></div></div><div class="product-orbit product-orbit-one"/><div class="product-orbit product-orbit-two"/><div class="product-spark">✳</div><div class="product-visual-bottom">СЕКРЕТАРЬ РАБОТАЕТ, ПОКА ВЫ ЗАНЯТЫ СВОИМ ДЕЛОМ</div></div></section>
      <section class="product-steps" id="how"><div class="product-section-heading"><span>01 / КАК ЭТО РАБОТАЕТ</span><h2>От первого «здравствуйте»<br />до записи в календаре.</h2></div><div class="product-step-grid"><article><b>01</b><span>✦</span><h3>Клиент пишет</h3><p>На вашей странице записи или в виджете на сайте. Вопросы можно задать в любое время.</p></article><article><b>02</b><span>◷</span><h3>AI находит время</h3><p>Уточняет услугу, имя и телефон, проверяет расписание и предлагает свободный слот.</p></article><article><b>03</b><span>▦</span><h3>Вы видите запись</h3><p>Подтверждённый визит сразу появляется в календаре. Расписание остаётся под вашим контролем.</p></article></div></section>
      <section class="product-demo-promo"><div><span>02 / ПОПРОБУЙТЕ САМИ</span><h2>Откройте демо<br />и запишитесь<br /><em>как клиент.</em></h2><p>Мы сохранили сайт вымышленной студии «Линия». Нажмите «Записаться», пообщайтесь с секретарём и посмотрите весь путь клиента.</p><a class="product-button product-button-light" href="/demo">Открыть демо <span>↗</span></a></div><div class="product-demo-preview"><div class="preview-header">✳ линия.<small>ДЕМО-СТУДИЯ</small></div><div class="preview-hero">Красота<br />в вашем <i>ритме.</i></div><div class="preview-chat">✦ &nbsp;Записаться</div></div></section>
      <section class="product-pricing" id="plans"><div class="product-section-heading"><span>03 / ТАРИФЫ</span><h2>Простой старт.<br />Понятная цена.</h2><p>Первые 14 дней бесплатно. После пробного периода оплата и продление подтверждаются вручную.</p></div><div class="product-price-grid"><article><div class="price-label">AI-ЗАПИСЬ</div><h3>Для записи клиентов</h3><div class="price-number">499 ₽<small>/ месяц</small></div><ul><li>AI-секретарь и форма записи</li><li>Календарь, услуги и рабочие часы</li><li>Страница записи и виджет</li><li>До 1000 ответов AI за оплаченный период</li></ul><a class="product-button" href="/register?plan=booking">Начать бесплатно <span>↗</span></a></article><article class="price-featured"><div class="price-label">ЗАПИСЬ + ФИНАНСЫ <span>ВСЁ ВМЕСТЕ</span></div><h3>Для контроля бизнеса</h3><div class="price-number">999 ₽<small>/ месяц</small></div><ul><li>Всё из тарифа «AI-запись»</li><li>Доходы и расходы в одном списке</li><li>Оплата записи без повторного учёта</li><li>Месячная сводка и результат</li></ul><a class="product-button" href="/register?plan=finance">Начать бесплатно <span>↗</span></a></article></div><p class="product-price-note">После окончания доступа запись продолжит работать. AI ответит до 100 раз за календарный месяц, затем клиент увидит обычную форму. Новые телефоны в кабинете будут скрыты до продления.</p></section>
    </main><footer class="product-footer"><strong>✳ alzy</strong><span>AI-секретарь для малого бизнеса</span><a href="/app">Войти в кабинет →</a></footer>
  </div>;
}
